barnardos/design-system

.stylelintrc.json
src/components/Navigation/index.css
src/components/Navigation/index.js
src/layouts/index.css
src/layouts/index.js
src/pages/index.css
src/pages/index.js
src/pages/principles.js
src/pages/typography-and-layout.js

Closes #25 
Two commits - one for adding the navigation, the other for adding the new principles section.
A further PR will add an introduction to the home page.

Add principles

---

src/components/Link/index.js
src/components/Navigation/index.js
src/pages/colour.js
src/pages/components.js
src/pages/principles.js
src/pages/typography-and-layout.js

Provides a method for linking to resources, regardless of location or type.
Uses browser/device defaults for styling as per usability guidelines.
Closes #47

Add Link component

---

src/pages/index.js

Fix emphasis on some service users being children

---

.stylelintrc.json
src/pages/index.css

Fix example border not showing up on iOS

---

.stylelintrc.json
package.json
yarn.lock

Add linting of CSS empty lines

---

src/pages/index.css

Fix Example pseudo content not showing in IE11

---

src/components/AttentionGrabbingLink/index.css
src/pages/components.js

Additionally, add underline in all states of interaction, to adhere to usability findings.
Closes #58

Fix differentiation between AttentionGrabbingLink and SubmitAction

---

src/components/Navigation/index.js
src/components/Swatches/index.css
src/components/Swatches/index.js
src/pages/colour.js
src/pages/index.js

Use JSX spread attributes so that the leaf components needn't change.
Closes #50

Refactor components to accept copy as props

---

src/components/Swatch/index.css

Fix misalignment of Swatch outline

---

package.json
src/layouts/index.js
src/pages/colour.js
src/pages/components.js
src/pages/gathering-input.js
src/pages/index.js
src/pages/principles.js
src/pages/typography-and-layout.js
yarn.lock

Pages were missing:
- specificing language
- page titles
These are required for accessibility.
Closes #72

Fix title and lang

---

src/components/MultiSelectionControlGroup/index.js
src/components/MultilineTextControl/index.css
src/components/SelectionControl/index.css
src/components/SelectionControl/index.js
src/components/SelectionControlGroup/index.css
src/components/SelectionControlGroup/index.js
src/components/SingleSelectionControlGroup/index.js
src/components/TextControl/index.css
src/pages/gathering-input.js

Add SelectionControl components

---

src/pages/requesting-information.js

Fix limit of choice options

---

src/components/AttentionGrabbingLink/index.css
src/components/HeadingOne/index.css
src/components/HeadingTwo/index.css
src/components/Lede/index.css
src/components/ListItem/index.css
src/components/Paragraph/index.css
src/components/Submit/index.css
src/components/Swatch/index.css
src/components/Swatches/index.css
src/components/Title/index.css
src/components/UnorderedList/index.css

Fix linting of BEM architecture

---

src/pages/typography-and-layout.js

Fix guidance of optimal line length

---

.stylelintrc.json
src/components/AttentionGrabbingLink/index.css
src/components/Header/index.css
src/components/Navigation/index.css
src/components/Submit/index.css
src/components/SubmitSearchControl/index.css
src/components/Swatch/index.css
src/pages/index.css

Fix inconsistent hex color length

---

src/pages/colour.js
src/pages/linking.js
src/pages/requesting-information.js
src/pages/typography-and-layout.js
src/pages/wayfinding.js

Add links to research and code

---

src/components/AttentionGrabbingLink/index.css
src/components/Header/index.css
src/components/Navigation/index.css
src/components/Submit/index.css
src/components/SubmitSearchControl/index.css
src/pages/colour.js

The print versions of purple and green were accidentally used.
Closes #107

Fix colors

---

src/components/Navigation/index.css
src/components/Navigation/index.js
src/components/SubmitSearchControl/index.css
src/components/SubmitSearchControl/index.js
src/pages/wayfinding.js

Fix relatively positioned examples

---

.babelrc
.circleci/config.yml
.gitignore
jest.config.js
package.json
src/__tests__/e2e.test.js
src/components/DesignSystemNavigation/index.js
src/components/Title/index.js
yarn.lock

Happy path through the design system:
- can view landing page
- can view sub pages
Closes #106

Add initial e2e tests

---

package.json
src/components/HeadingOne/index.js
src/components/HeadingTwo/index.js
src/utils/slugifyNode.js
yarn.lock

Make it easier to link to sections
Closes #97

Add anchors to Heading* components

---

src/pages/index.js
src/pages/writing-content.js

Add writing content guidelines

---

src/components/Command/index.css
src/components/Command/index.js
src/components/Filter/cross.svg
src/components/Filter/index.css
src/components/Filter/index.js
src/components/Navigation/index.css
src/components/Navigation/index.js
src/components/SubmitControls/index.css
src/components/SubmitSearchControl/index.css
src/components/SubmitSearchControl/index.js
src/components/Title/index.js
src/pages/filtering.js
src/pages/index.js

Add filters

---

src/components/DesignSystemNavigation/index.css
src/pages/index.js

Make it clearer who it's for, and that it's a guide.
Closes #129

Add  introduction

---

src/pages/requesting-information.js

Fix example form length

---

src/pages/principles.js

Add two additional principles:
- keep it simple
- embrace digital
While fleshing out the existing four principles.
Closes #32

Expand principles

---

src/components/Navigation/index.css
src/components/Navigation/index.js

Fix wayfinding examples

---

.stylelintrc.json
src/components/Swatch/index.css
src/components/Swatch/index.js
src/components/Swatches/index.css
src/pages/colour.js
src/pages/index.css

Communicate rules and provide suggestions of use.
Closes #112 
Closes #76

Fix communication of color

---

src/proportional-scale.css

Fix proportional scale CSS comment

---

src/__tests__/e2e.test.js
src/components/Lede/index.css
src/pages/getting-started.js
src/pages/guidance.js
src/pages/guidance/colour.js
src/pages/guidance/filtering.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/linking.js
src/pages/guidance/requesting-information.js
src/pages/guidance/wayfinding.js
src/pages/guidance/writing-content.js
src/pages/index.css
src/pages/index.js
src/pages/principles.js

Add getting started

---

src/pages/index.css

Fix typography figure

---

src/pages/guidance/layout-and-typography.js

Fix optimal line-length guidance

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/USER_STORY.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE

Fulfills GitHub's six point criteria.
Follows the principles of:
- start small
- iterate based on feedback
Closes #38

Add community guidelines

---

.stylelintrc.json
src/components/BackLink/index.css
src/components/BackLink/index.js
src/components/BackLink/triangle.svg
src/pages/guidance/linking.js

Add BackLink

---

src/components/StartLink/index.css
src/components/StartLink/index.js
src/pages/guidance/linking.js

Add StartLink

---

src/components/CurrencyControl/index.css
src/components/CurrencyControl/index.js
src/pages/guidance/requesting-information.js

Add CurrencyControl

---

src/pages/guidance/requesting-information.js

Fix missing guidance for control groups

---

VISION.md

Closes https://github.com/barnardos/design-system/issues/159

Add vision

---

src/__tests__/e2e.test.js
yarn.lock

Fix intermittently failing tests

---

src/pages/guidance/colour.js

Fix colour spelling

---

src/pages/getting-started.js

Fix getting started contact

---

src/pages/guidance/filtering.js
src/pages/principles.js

Fix broken internal links

---

.stylelintrc.json
src/components/Command/index.css
src/components/Submit/index.css
src/components/SubmitSearchControl/index.css
src/pages/guidance/colour.js

Fix dropdown contrast

---

VISION.md

Fix typo in VISION doc

---

src/components/AnyOfManyChoiceControl/index.js
src/components/ChoiceControl/index.js
src/components/CurrencyControl/index.css
src/components/CurrencyControl/index.js
src/components/DateControl/index.css
src/components/DateControl/index.js
src/components/MultilineTextControl/index.css
src/components/MultilineTextControl/index.js
src/components/OfManyChoiceControl/index.css
src/components/OfManyChoiceControl/index.js
src/components/OneOfManyChoiceControl/index.js
src/components/SinglelineTextControl/index.css
src/components/SinglelineTextControl/index.js
src/components/SubmitControls/index.js
src/components/SubmitSearchControl/index.js
src/pages/guidance/colour.js
src/pages/guidance/filtering.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/requesting-information.js

Fix proptype warnings

---

src/pages/index.js

Fix link destination communication

---

src/components/DesignSystemNavigation/index.css
src/components/DesignSystemNavigation/index.js

Fix emphasis of DesignSystemNavigation

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/STORY.md

Fix issue templates

---

src/components/Header/index.js
src/layouts/index.css
src/layouts/index.js
src/pages/guidance/wayfinding.js
src/pages/index.css

Add branding

---

src/pages/guidance/colour.js

Fix colour explanation

---

src/pages/guidance/requesting-information.js

As freetext Address and Fullname misaligned with proposed data model
Closes #225

Fix labels in some examples

---

.circleci/config.yml

Fix CircleCi cache

---

src/pages/guidance/colour.js

Fix tint and shade color guidance

---

src/pages/getting-started.js

The DS is for designers and developers working together.
Closes #223

Fix communication of audience

---

src/pages/index.css

Fix figure caption wrapping

---

.gitignore
package-lock.json
src/pages/getting-started.js
src/pages/guidance.js
src/pages/guidance/accessibility.js

Add accessibility guidance

---

src/pages/guidance/accessibility.js

Fix accessibility page title

---

src/pages/guidance.js
src/pages/guidance/iconography.js

Add iconography

---

src/pages/guidance.js
src/pages/guidance/film-and-photography.js

Add film and photography guidance

---

.stylelintrc.json
src/components/DesignSystemNavigation/index.css
src/components/DesignSystemNavigation/index.js
src/components/Layout/index.css
src/components/Layout/index.js
src/components/Paragraph/index.css
src/components/UnorderedList/index.css
src/pages/guidance.js
src/pages/guidance/colour.js
src/pages/guidance/filtering.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/linking.js
src/pages/guidance/requesting-information.js
src/pages/guidance/wayfinding.js
src/pages/guidance/writing-content.js
src/pages/index.css

Fix navigation styles

---

src/pages/guidance.js
src/pages/guidance/developer-tools.js

Add developer tools guidance

---

src/pages/guidance/requesting-information.js

Fix MultiLineTextControl label

---

src/components/CurrencyControl/index.css
src/components/DateControl/index.css
src/components/MultilineTextControl/index.css
src/components/Navigation/index.css
src/components/OfManyChoiceControl/index.css
src/components/SinglelineTextControl/index.css
src/components/Swatch/index.css

Remove redundant CSS comments

---

src/pages/guidance/accessibility.js
src/pages/guidance/developer-tools.js
src/pages/guidance/iconography.js
src/pages/guidance/writing-content.js

Fix missing links

---

src/pages/guidance/film-and-photography.js

Closes #270 
Accessibility guidance will be addressed in #249

Fix film and photography points

---

src/pages/getting-started.js

Update content and link to workplace

---

src/components/Command/index.js
src/components/Header/index.js
src/components/Submit/index.js

Refactor to implicit returns

---

package-lock.json
src/pages/guidance/colour.js
src/pages/guidance/developer-tools.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/navigating.js
src/pages/guidance/patterns.js
src/pages/guidance/requesting-information.js
src/pages/guidance/writing-content.js

Closes https://github.com/barnardos/design-system/issues/311

Fix ToC links returning to home page

---

src/components/ConditionalControls/index.css
src/components/ConditionalControls/index.js
src/pages/guidance/requesting-information.js

Closes https://github.com/barnardos/design-system/issues/86
This example implementation just shows how the reveal would work.

Add ConditionalControls

---

src/components/Figure/index.css
src/components/Figure/index.js
src/components/Image/index.css
src/components/Image/index.js
src/pages/guidance.js
src/pages/guidance/displaying-information.js

Closes https://github.com/barnardos/design-system/issues/300

Add Figure

---

src/components/PullQuote/index.css
src/components/PullQuote/index.js
src/custom-properties.css
src/pages/guidance/displaying-information.js

Closes https://github.com/barnardos/design-system/issues/252

Add PullQuote

---

src/components/AttentionGrabbingLink/index.js
src/pages/guidance/navigating.js

To be consistent with other components.
Closes #315

Fix American English colour prop in AGL

---

src/components/Layout/index.css
src/components/Quote/index.css
src/components/Quote/index.js
src/components/TableOfContents/index.css
src/pages/guidance/displaying-information.js

Fix support for imaging on Quote

---

src/components/AttentionGrabbingQuote/index.css
src/components/AttentionGrabbingQuote/index.js
src/components/Quote/index.css
src/pages/guidance/displaying-information.js

Add AttentionGrabbingQuote

---

src/components/Layout/index.css
src/components/Layout/index.js
src/components/TableOfContents/index.css
src/components/TableOfContents/index.js
src/pages/guidance/colour.js
src/pages/guidance/developer-tools.js
src/pages/guidance/displaying-information.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/navigating.js
src/pages/guidance/patterns.js
src/pages/guidance/requesting-information.js
src/pages/guidance/writing-content.js
src/pages/index.css
src/reset.css

To be more functional through being sticky and smooth scrolling.
Closes https://github.com/barnardos/design-system/issues/323

Fix ToC behaviour

---

src/components/UnorderedListItem/bullet.svg
src/components/UnorderedListItem/index.css
src/components/UnorderedListItem/index.js
src/pages/guidance/displaying-information.js
src/pages/guidance/writing-content.js

Closes https://github.com/barnardos/design-system/issues/325

Add UnorderedListItem

---

src/pages/guidance/layout-and-typography.js
src/pages/index.css

Add layout figures

---

src/pages/guidance/patterns.js

Fix footer navigation

---

src/components/Swatch/index.css
src/pages/guidance/colour.js

Reintroduce circle swatches to be more on brand.
Closes #332

Fix branding of colour guidance

---

.eslintrc.json
package-lock.json

By specifying react version in config.

Fix eslint-plugin-react warning

---

package-lock.json
package.json

Fix ToC anchor links

---

src/components/Caption/index.css

Fix caption spacing

---

src/pages/guidance/displaying-information.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/navigating.js
src/pages/guidance/requesting-information.js

Fix component names

---

package-lock.json
package.json
src/components/Pagination/index.css
src/components/Pagination/index.js
src/components/Pagination/triangle.svg
src/pages/guidance/navigating.js

Add Pagination

---

src/components/Feedback/index.css
src/components/Feedback/index.js
src/components/Layout/index.css
src/components/Layout/index.js

Add Feedback

---

src/components/UnorderedListItem/bullet.svg
src/components/UnorderedListItem/index.css

Fix UnorderedListItem style

---

package-lock.json
package.json
src/components/AttentionGrabbingLink/index.css
src/components/DonateLink/index.css
src/components/DonateLink/index.js
src/components/ProgressLink/index.css
src/pages/guidance/navigating.js

Add DonateLink

---

src/pages/guidance/layout-and-typography.js
src/pages/index.css

Fix communication of white space in layout

---

src/pages/guidance/layout-and-typography.js

Fix communication of typography guidance

---

src/custom-properties.css
src/pages/guidance/layout-and-typography.js

Fix line-height increments

---

src/components/OfManyChoiceControl/index.css

Fix choice control line height

---

src/pages/guidance/colour.js
src/pages/guidance/layout-and-typography.js

Fix colour communication

---

_redirects

Add domain redirect

---

src/pages/guidance/navigating.js

Fix attention grabbing link guidance

---

src/components/Footer/index.css
src/components/Footer/index.js
src/components/Menu/index.css
src/pages/guidance/navigating.js
src/pages/guidance/patterns.js

Fix Header & Footer navigation guidance

---

src/pages/guidance/navigating.js

Fix link case guidance

---

.browserslistrc
src/pages/guidance/developer-tools.js

Fix browserslist config

---

package-lock.json
package.json
src/components/AttentionGrabbingLink/index.css
src/components/Command/index.css
src/components/DonateLink/index.css
src/components/Pagination/index.css
src/components/ProgressLink/index.css
src/components/StartLink/index.css
src/components/Submit/index.css

Fix white space for revised line heights

---

src/components/AttentionGrabbingCard/index.css
src/components/AttentionGrabbingCard/index.js
src/components/AttentionGrabbingLink/index.css
src/components/AttentionGrabbingLink/index.js
src/components/Card/index.css
src/pages/guidance/navigating.js

Add Attention Grabbing Card

---

src/pages/guidance/requesting-information.js

Fix communication of grouping text controls

---

src/components/Cite/index.css
src/components/Cite/index.js
src/pages/guidance/accessibility.js
src/pages/guidance/colour.js
src/pages/guidance/developer-tools.js
src/pages/guidance/displaying-information.js
src/pages/guidance/film-and-photography.js
src/pages/guidance/iconography.js
src/pages/guidance/layout-and-typography.js
src/pages/guidance/navigating.js
src/pages/guidance/patterns.js
src/pages/guidance/requesting-information.js
src/pages/guidance/writing-content.js

Fix emphasis of code and research links

---

src/components/Header/index.css
src/components/Header/index.js
src/components/Menu/index.css
src/components/Menu/index.js
src/pages/guidance/navigating.js

Add secondary menu example

---

src/components/AttentionGrabbingLink/index.css
src/components/BackLink/index.css
src/components/Breadcrumbs/index.css
src/components/Card/index.css
src/components/DesignSystemNavigation/index.css
src/components/DonateLink/index.css
src/components/Layout/index.js
src/components/Link/index.css
src/components/Link/index.js
src/components/Pagination/index.css
src/components/ProgressLink/index.css
src/components/StartLink/index.css
src/components/SubmitControls/index.css
src/components/TableOfContents/index.css
src/pages/getting-started.js
src/pages/guidance/accessibility.js
src/pages/guidance/iconography.js
src/pages/guidance/patterns.js
src/pages/principles.js

Add link colour and hover behaviour

---

src/pages/guidance/displaying-information.js

Fix quote guidance

---

src/components/AttentionGrabbingCard/index.css

Fix AGC spacing

---

src/components/TableOfContents/index.css
src/pages/guidance/navigating.js

Add Table Of Contents guidance

---

src/pages/guidance/navigating.js

Closes https://github.com/barnardos/design-system/issues/443

Fix ToC overlapping content

---

src/pages/guidance/patterns.js

Add requesting name pattern

---

src/pages/guidance/patterns.js
src/pages/guidance/requesting-information.js

Add preventing spam guidance

---

src/pages/index.js
src/pages/principles.js

Fix principles order

---

src/pages/gathering-information.js
src/pages/index.js

Fix requesting information label

---

src/pages/displaying-content.js
src/pages/typography.js

Fix type component location

---

src/components/DesignSystemLayout/index.js
src/pages/getting-started.js

Fix getting started content

---

.eslintrc.json
package-lock.json
package.json
src/pages/code-quality.js

Use eslint config barnardos

---

README.md

Add links to analytics

---

src/components/DesignSystemLayout/index.js
src/pages/navigating.js

I've changed the component so that it must be able to display the current year on its own.
Closes #478

Fix copyright date 

---

src/components/TypeFigures/index.css
src/components/TypeFigures/index.js
src/pages/content.js
src/pages/typography.js
src/pages/viewport-scale.js

By adding a visual example of the scale itself.
Closes #487

Fix communication of type scale

---

src/components/Hint/index.css
src/components/Topic/index.css
src/components/Topic/index.js
src/pages/asking-for-names.js
src/pages/brand-assets.js
src/pages/code-quality.js
src/pages/colour.js
src/pages/considerations.js
src/pages/content.js
src/pages/film-and-photography.js
src/pages/filtering.js
src/pages/forms.js
src/pages/future-proof-code.js
src/pages/iconography.js
src/pages/navigation.js
src/pages/preventing-spam.js
src/pages/spacing-and-layout.js
src/pages/spelling.js
src/pages/style.js
src/pages/typography.js
src/pages/viewport-scale.js

Fix wayfinding

---

src/components/Pagination/index.css
src/components/Pagination/index.js
src/components/Pagination/triangle.svg
src/pages/code-quality.js
src/pages/colour.js
src/pages/considerations.js
src/pages/future-proof-code.js
src/pages/navigation.js
src/pages/spacing-and-layout.js
src/pages/spelling.js
src/pages/style.js
src/pages/typography.js
src/pages/viewport-scale.js

Add ability to move sideways through standards

---

package-lock.json
package.json
postcss.config.js
src/components/ComponentsIndex/index.css
src/components/DateInput/index.css
src/components/DateInput/index.js
src/components/DesignSystemNavigations/index.css
src/components/Header/index.css
src/components/Index/index.css
src/components/Pagination/index.css
src/components/Promo/index.css
src/components/Promos/index.css
src/components/SignpostLink/index.css
src/components/StartLink/index.css
src/components/Swatches/index.css
src/pages/navigation.js

Fix ie issues

---

src/components/ColourFigure/index.css
src/components/ColourFigure/index.js
src/components/ColourGreyFigure/index.css
src/components/ColourGreyFigure/index.js
src/pages/colour.js
src/pages/considerations.js
src/pages/content.js
src/pages/forms.js
src/pages/navigation.js
src/pages/spacing-and-layout.js
src/pages/typography.js

Fix communication of colour scale

---

src/components/DesignSystemLayout/index.js
src/components/SkipLink/index.css
src/components/SkipLink/index.js
src/pages/navigation.js

Add Skip Link

---

src/components/custom-properties.css

Fix line heights of upper type scale

---

src/pages/navigation.js

Ref: https://github.com/barnardos/design-system/pull/532

Fix SkipLink links

---

src/components/Label/index.css
src/components/Label/index.js
src/components/Switch/index.css
src/components/Switch/index.js

So that they are more accessible.
Closes #485

Fix click area size of choices

---

src/pages/content.js

Fix subheading typo

---

src/components/Header/index.js

Fix logo link

---

src/components/CurrencyInput/index.js
src/components/Label/index.js
src/components/Switch/index.js
src/components/TextArea/index.js
src/components/TextInput/index.js

Fix label on Date input

---

src/components/Label/index.css
src/components/Label/index.js
src/components/Switch/index.css
src/components/Switch/index.js

Fix Switch checked state

---

src/components/Field/index.css

Fix Field gap

---

README.md

Fix path in importing CSS path

---

src/components/Content/index.css
src/components/ContentWithMenu/index.css
src/pages/forms.js

To prevent overlapping content.
Closes #565

Fix Content With Menu

---

src/components/BackLink/index.css
src/components/BackLink/triangle.svg
src/components/Breadcrumbs/index.css

To reserve triangle for Details.
Closes #564

Fix BackLink style

---

src/pages/spacing-and-layout.js
src/pages/typography.js

Fix missing design standards research link

---

src/pages/forms.js

Fix guidance on disabled Submit

---

package-lock.json
package.json
src/components/CurrencyInput/index.css

To make the prefix feel more connected.
Closes #563

Fix Currency Input

---

src/components/BlockQuote/index.js
src/components/ContentsMenu/index.js
src/components/DesignSystemNavigation/index.js
src/components/Fact/index.js
src/components/ProminentBlockQuote/index.js
src/components/ProminentLink/index.js
src/components/ProminentPromo/index.js
src/components/PullQuote/index.js
src/components/Swatch/index.js

To make them consistent across all components.
Closes #575

Refactor dynamic class names

---

src/components/Pagination/index.js

To remove code duplication.
Closes #589

Refactor Pagination

---

src/components/Breadcrumbs/index.css

Fix Breadcrumbs ident on wrap

---

src/pages/brand-assets.js

Fix link to favicon in Brand assets

---

src/pages/future-proof-code.js

Fix link to future-proof code research

---

CHANGELOG.md

Prepare 0.2.0 changelog

---

package-lock.json
package.json

Prepare 0.2.0

---

src/components/Breadcrumbs/index.css
src/components/Footer/index.css
src/components/Header/index.css
src/components/Layout/index.css
src/components/Main/index.css
src/components/Section/index.css
src/components/SkipLink/index.css
src/pages/navigation.js

As this is the most common use case.
Closes #595

Fix Layout to be responsible for page padding

---

src/components/Menu/index.css
src/components/Search/index.css
src/pages/navigation.js

To match the evolving design.
Closes #604

Fix Menu and Search look

---

src/pages/content.js
src/pages/forms.js
src/pages/images-and-videos.js
src/pages/index.js

Add audience information

---

src/pages/considerations.js
src/pages/future-proof-code.js
src/pages/index.js
src/pages/performance.js

Add performance guidance

---

src/components/NumberedList/index.css
src/components/NumberedList/index.js
src/pages/considerations.js
src/pages/getting-started.js
src/pages/iconography.js
src/pages/index.js
src/pages/sketch-assets.js
src/pages/web-assets.js

Add Sketch assets guidance

---

src/pages/content.js

Fix pull quote link

---

src/pages/formatting.js
src/pages/index.js
src/pages/maintenance.js
src/pages/reading-age.js
src/pages/voice-and-tone.js

Fix writing content standards

---

src/components/Conditional/index.js
src/components/Filter/index.css
src/components/Filter/index.js

Refactor to use hooks

---

src/components/DesignSystemNavigation/index.css
src/components/DesignSystemNavigations/index.css
src/components/Details/index.css
src/components/Details/index.js
src/components/Feedback/index.css
src/components/Feedback/index.js
src/components/Link/index.css
src/components/Link/index.js
src/components/Promos/index.css
src/components/SignpostLink/index.css
src/pages/assets.js
src/pages/assets/iconography.js
src/pages/assets/images-and-videos.js
src/pages/assets/sketch-assets.js
src/pages/assets/web-assets.js
src/pages/getting-started.js
src/pages/index.js
src/pages/patterns.js
src/pages/patterns/asking-for-names.js
src/pages/patterns/filtering.js
src/pages/patterns/preventing-spam.js

Fix homepage structure

---

src/components/Feedback/index.css
src/components/Footer/index.css

Fix footer style

---

src/components/ComponentsIndexes/index.css
src/components/Main/index.js
src/components/Menu/index.css
src/components/Preformatted/index.js
src/components/SkipLink/index.js
src/pages/index.js
src/pages/navigation.js
src/pages/structure.js

Like Layout, Site and Main.
Closes #583

Fix communication of structure components

---

CHANGELOG.md
package-lock.json
package.json
src/components/index.js

Prepare 0.3.0

---

src/components/BackLink/index.css
src/components/ComponentsIndex/index.css
src/components/ContentsMenu/index.css
src/components/DesignSystemNavigation/index.css
src/components/Link/index.css
src/components/Pagination/index.css

Fix visited link

---

src/components/BlockQuote/index.css
src/components/BlockQuote/index.js

Fix blockquote look

---

src/pages/code-quality.js

Fix code quality communication

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/CHORE.md
.github/ISSUE_TEMPLATE/STORY.md

Improve issue templates

---

src/pages/content.js

Fix Topic guidance

---

src/components/Caption/index.css
src/components/Site/reset.css

Refactor to use consistent nesting

---

src/components/BackLink/index.css
src/components/Pagination/index.css
src/components/Pagination/index.js
src/components/SignpostLink/index.css
src/components/StartLink/index.css

Fix SignpostLink wrap on arrow viewports

---

src/components/Callout/index.css
src/components/Callout/index.js
src/pages/content.js

Add Callout

---

src/pages/colour.js

Fix opacity guidance

---

src/components/Command/index.css
src/components/ComponentsIndex/index.css
src/components/CurrencyInput/index.css
src/components/DateInput/index.css
src/components/Feedback/index.css
src/components/ProminentPromo/index.css
src/components/Promo/index.css
src/components/Search/index.css
src/components/Submit/index.css
src/components/TextArea/index.css
src/components/TextInput/index.css

Fix shadow direction

---

src/components/Command/index.css

Fix command look

---

src/components/Site/reset.css
src/components/SkipLink/index.css
src/components/Switch/index.css
src/components/custom-properties.css
src/pages/colour.js

Fix focus state colour

---

src/components/ComponentsIndexes/index.css
src/components/DesignSystemNavigations/index.css
src/components/Feedback/index.css
src/components/Footer/index.css
src/components/Header/index.css
src/components/Layout/index.css
src/components/Promos/index.css

Fix horizontal scroll bar appearing

---

src/components/Search/index.css
src/components/Submit/index.css

Fix submit look

---

package-lock.json
package.json
src/components/ComponentsIndexes/index.css
src/components/ContentHeader/index.css
src/components/Demo/index.css
src/components/DesignSystemNavigation/index.css
src/components/DesignSystemNavigations/index.css
src/components/Layout/index.css
src/components/ProminentPromo/index.css
src/components/Promo/index.css
src/components/Section/index.css
src/components/Site/reset.css
src/components/Site/viewport-scale.css
src/components/Submit/index.css
src/components/Title/index.css

Refactor to remove redundant stylelint command comments

---

src/components/Command/index.css

Fix command states

---

src/components/BlockQuote/index.css
src/components/BlockQuote/index.js

Fix BlockQuote missing trailing quote mark

---

src/components/DownloadLink/index.css
src/components/DownloadLink/index.js
src/pages/navigation.js

Add DownloadLink

---

src/components/Command/index.css
src/components/Promo/index.css
src/components/Submit/index.css

Fix submit states

---

src/components/ProminentCallout/index.css
src/components/ProminentCallout/index.js
src/pages/components/content.js

Add prominent callout

---

src/pages/assets/iconography.js
src/pages/assets/images-and-videos.js
src/pages/assets/sketch-assets.js
src/pages/assets/web-assets.js
src/pages/patterns/asking-for-names.js
src/pages/patterns/filtering.js
src/pages/patterns/preventing-spam.js

Fix pagination use

---

src/pages/getting-started.js

Fix getting started dead end

---

src/components/ContentsMenu/index.css
src/components/ContentsMenu/index.js
src/components/ErrorSummary/index.css
src/components/ErrorSummary/index.js
src/components/Feedback/index.css
src/components/Feedback/index.js
src/components/Header/index.css
src/components/ProminentCallout/index.css
src/components/ProminentCallout/index.js
src/components/ProminentTeaser/index.css
src/components/ProminentTeaser/index.js
src/components/Teaser/index.css
src/components/Teaser/index.js
src/pages/components/content.js
src/pages/components/navigation.js
src/pages/index.js

Fix title props

---

src/components/Breadcrumbs/index.css
src/components/ContentsMenu/index.css
src/components/Footer/index.css
src/components/Menu/index.css
src/components/Search/index.css
src/components/SignpostLink/index.css

Fix hit areas

---

src/pages/assets.js
src/pages/assets/generating-sketch-assets.js
src/pages/assets/images-and-videos.js
src/pages/assets/web-assets.js
src/pages/components/content.js
src/pages/components/forms.js
src/pages/components/navigation.js
src/pages/patterns.js
src/pages/patterns/asking-for-names.js
src/pages/patterns/filtering.js
src/pages/patterns/gathering-information.js
src/pages/standards.js
src/pages/standards/testing.js
src/pages/standards/viewport-scale.js

Fix guidance name location

---

gatsby-browser.js
package-lock.json
package.json
src/__tests__/a11y.test.js
src/components/DocSearch/index.css
src/components/DocSearch/index.js
src/components/Header/index.js
src/components/Page/index.js
src/pages/components/structure.js

Add search

---

src/pages/components/content.js

Fix callout headings

---

src/components/BlockQuote/index.css
src/components/BlockQuote/index.js
src/components/ColourFigure/index.css
src/components/Demo/index.css
src/components/ProminentBlockQuote/index.css

Refactor to use consistent nested at-rules

---

src/components/ContentsMenu/index.css

When too many items for viewport height.
Closes #701

Fix ContentsMenu scroll

---

src/components/Fieldset/index.js

Fix ErrorSummary jump to choices

---

src/pages/components/navigation.js

Add Teasers

---

src/components/BulletedList/index.css
src/components/Lede/index.css
src/components/NumberedList/index.css
src/components/Paragraph/index.css
src/components/ProminentCallout/index.css

Fix line length

---

src/components/Pagination/index.css
src/pages/patterns.js
src/pages/patterns/asking-for-names.js
src/pages/patterns/filtering.js
src/pages/patterns/gathering-information.js
src/pages/patterns/interacting-with-young-people.js

Add interacting pattern

---

src/pages/components/content.js
src/pages/components/navigation.js

Add sections

---

src/pages/components/content.js
src/pages/standards/typography.js

Fix typography link to type

---

src/pages/standards/typography.js

Fix body copy guidance

---

src/__tests__/a11y.test.js
src/components/Caption/index.css
src/components/Caption/index.js
src/components/Image/index.css
src/components/Image/index.js

Refactor caption

---

src/components/Video/index.css
src/components/Video/index.js
src/components/index.js
src/pages/components/content.js

Add how to display a video

---

package-lock.json
package.json
src/components/Details/index.css
src/pages/components/content.js

Add Details component

---

src/pages/components/forms.js

Fix error order

---

src/components/Header/index.js

Fix Header button semantics

---

src/components/Submit/index.js
src/pages/components/forms.js
src/pages/patterns/filtering.js

Fix Submit semantics

---

src/components/Filter/index.js
src/components/Trigger/index.css
src/components/Trigger/index.js
src/components/index.js
src/pages/components/forms.js

Fix Command name

---

src/components/Confirmation/index.css
src/components/Confirmation/index.js
src/pages/components/forms.js

Add confirmation

---

src/components/index.js

Fix export of Confirmation

---

src/components/Hero/index.css
src/components/Hero/index.js
src/pages/index.js

Fix Hero to accept explicit props

---

src/pages/patterns.js
src/pages/patterns/interacting-with-young-people.js
src/pages/patterns/preventing-spam.js
src/pages/patterns/start-page.js

Add start page pattern

---

CHANGELOG.md
package-lock.json
package.json

Prepare 0.5.0

---

CHANGELOG.md
package-lock.json
package.json

Prepare 0.5.1

---

src/pages/example-product.js
src/pages/index.js

Add example product info

---

src/components/Code/index.css

Fix Code style

---

src/components/ProminentTeaser/index.css

Fix Prominent Teaser

---

src/pages/standards/testing.js

Fix accessibility testing guidance

---

src/pages/standards/colour.js

Fix tint exception

---

src/components/Demo/index.css

Fix spacing shadow

---

src/components/ProminentBlockQuote/index.css

Fix Prominent Blockquote width

---

src/components/ContentsMenu/index.css
src/components/LandingMenu/index.css

Fix Menu padding

---

src/__tests__/a11y.test.js
src/pages/components/content.js
src/pages/patterns/interacting-with-young-people.js
src/pages/standards.js
src/pages/standards/typography.js

Fix typography guidance

---

src/components/BlockQuote/index.css
src/components/BlockQuote/index.js
src/components/Image/index.css
src/components/Image/index.js
src/components/ProminentTeaser/index.css
src/components/ProminentTeaser/index.js
src/components/Teaser/index.css
src/components/Teaser/index.js

Fix Teaser image intrinsic ratio

---

src/pages/index.js

Fix how to contribute

---

src/components/LandingMenu/index.css
src/pages/standards/colour.js

Fix colour guidance

---

src/components/SpacingFigure/index.js
src/pages/standards/spacing-and-layout.js

Fix spacing layout guidance

---

src/pages/index.js
src/pages/product-kit.js

Fix example product name

---

src/pages/getting-started.js

Fix getting start guidance

---

package-lock.json
package.json

Prepare 0.6.0

---

src/pages/assets/generating-sketch-assets.js

Fix sketch link

---

src/components/SignpostLink/index.css

Fix signpost chevron wrapping

---

src/pages/index.js

Fix homepage teaser order

---

src/pages/index.js

Fix Get involved list

---

src/pages/assets/web-assets.js

Fix web assets size

---

src/pages/components.js

Fix components signpost

---

.github/CONTRIBUTING.md

Add releasing notes

---

src/pages/assets/generating-sketch-assets.js
src/pages/getting-started.js
src/pages/index.js
src/pages/product-kit.js

Fix product kit landing

---

src/components/DocSearch/index.js
src/components/Page/index.js
src/components/Search/index.js

Fix DocSearch button

---

src/pages/product-kit.js

Fix product kit landing content

---

src/pages/404.js

Add 404 page

---

src/components/Page/index.js
src/components/Site/index.js
src/pages/index.js

Fix page title endings

---

src/pages/assets.js
src/pages/assets/sketch-assets.js
src/pages/assets/web-assets.js
src/pages/components.js
src/pages/getting-started.js
src/pages/index.js
src/pages/patterns.js
src/pages/principles.js
src/pages/product-kit.js
src/pages/standards.js
src/pages/standards/iconography.js
src/pages/standards/images-and-videos.js
src/pages/standards/spacing-and-layout.js

Fix section teasers and ledes

---

src/pages/components/content.js
src/pages/components/forms.js
src/pages/components/navigation.js
src/pages/components/structure.js
src/pages/standards/iconography.js

Fix guidance differentiation

---

src/pages/patterns/gathering-information.js

Closes #840
Closes #843
Closes #848

Fix asking for names guidance

---

src/pages/patterns/gathering-information.js

Closes: Incremental solution will progress to subsequent issues being closed.

Fix gathering information guidance

---

src/pages/components/forms.js
src/pages/components/navigation.js
src/pages/components/structure.js

fix-missing-research

---

tsconfig.json

Adds tsconfig.json so module is read correctly

---

CHANGELOG.md
package-lock.json
package.json

Bump version so we can publish import fix
